### ISSUE TITLE
This is outstanding! A few ideas too (Element.matches())

### ISSUE THREAD

**Issue by Offroaders123** [BenjaminAster/Better-TypeScript#1]
Just have to say, thank you for making this! These have been headaches I've run into too, so this will be great to test things out with.

Service Worker typings have really been a pain to use, can't wait to try this out for that.

Another one that would be great to have in TypeScript, which I'm not sure about if it's possible, type inference and type parameters for `Element.matches()`? The workaround I've been using for it is to use a similarly structured, yet more verbose `elementReference instanceof HTMLElementClass` kind of check. My code previously used `elementReference.matches("tag-name")`, but this simply returns a boolean, and it also doesn't cast the type inside of the `if` block either. Maybe `asserts` could work? I'll try to see if I can figure it out too.

Again, great work here! 😃

**Comment by BenjaminAster** [comment]
Hmmm... I played around a bit with it; I really think it's not possible to "change" the type of a variable that has already been declared just by calling a method on it. It works with `instanceof` because TypeScript itself is smart enough to understand that if `element instanceof HTMLWhateverElement` returns true, `element` must be a `HTMLWhateverElement`, so
```typescript
const element = document.querySelector(".foo");
if (element instanceof HTMLAnchorElement) {
    element.href = "https://alskdjf";
}
```
works; I don't think it's possible to achieve the same with an `element.matches()`, but I might also be wrong, so if you have any ideas how it would be possible, go ahead and play around a bit with it yourself.

**Comment by BenjaminAster** [comment]
But to be honest, I think `if (element instanceof HTMLWhateverElement)` isn't even that hacky or verbose; I think it's actually quite readable, so imo there's not really a point in making `.matches()` being able to do the same thing.

**Comment by Offroaders123** [comment]
I think I was using it before because I was detecting the current state of the element using the selector, rather than using its JavaScript properties. While both work, using the JS side to calculate that information might make more sense than checking its selector. But, I do like both ways still.

Here's the kind of setup I was using it for before. It would both check if it's the right tag, and check its location in the HTML.

This is just an arbitrary example:

```js
if (element.matches("my-component > dialog[open]")){
  element.close();
}
```

Here's an equivalent way while using `instanceof` / element properties instead, which satisfies the type checking:

```js
if (element instanceof HTMLDialogElement && element.matches("my-component > :scope") && element.open){
  element.close();
}
```

I think I still do like the `Element.matches()` one more actually, but maybe it's more of a code-smell setup, if the surrounding code I'm using maybe shouldn't have to use that syntax?

**Comment by Offroaders123** [comment]
No way! Was working on another project when I realized how to do it. I really like it! It works very similarly to the type definitions for `ParentNode.querySelector()`.

```ts
// Inspired by `lib.dom.d.ts` definitions for `ParentNode.querySelector()`

declare global {
  interface Element {
    matches<K extends keyof HTMLElementTagNameMap>(selectors: K): this is HTMLElementTagNameMap[K];
    matches<K extends keyof SVGElementTagNameMap>(selectors: K): this is SVGElementTagNameMap[K];
    matches<E extends Element = Element>(selectors: string): this is E;
  }
}

declare const myElement: Element;

if (myElement.matches("div")){
  myElement; // HTMLDivElement
}

if (myElement.matches<HTMLDivElement>("dialog > div")){
  myElement; // HTMLDivElement
}

if (myElement.matches("rect")){
  myElement; // SVGRectElement
}

if (myElement.matches<SVGRectElement>("svg > g > rect")){
  myElement; // SVGRectElement
}

if (myElement.matches("unknown-tag")){
  myElement; // Element
}

document.querySelector("div"); // HTMLDivElement
document.querySelector("gg"); // Element

export {};
```

**Comment by BenjaminAster** [comment]
This is incredible! I really didn't think it was possible at all. I included the types in version `0.0.5` now.

Instead of `{HTML/SVG}ElementTagNameMap[K]` I used my `BetterTypeScript.GetElementNameFromSelector<K>` "function" that I also use for `.querySelector()`, so stuff like `.matches("dialog > div")` or `.matches("dialog[open]")` works out-of-the-box now without an ugly `.matches<HTMLWhateverElement>(selector)` type parameter.

**Comment by Offroaders123** [comment]
Awesome! I'm glad it works too. Thanks for adding it to the type definitions, it's so neat to be able to use it like this now.

**Comment by Offroaders123** [comment]
Was working on my own project, and I found an issue with the current types for the generic parameters. If you have an `if` statement that checks the value when the `Element.matches()` call is not matched as `true`, then it was falling back to the value `never`, rather than just using the previous scope of the type at that location.

```ts
declare const noice: Element;

if (noice.matches("a")){
  noice;

  if (noice.matches("[href]")){
    noice;
  } else {
    // @ts-expect-error
    noice.href = ""; // never
  }
} else {
  noice;
}

if (noice.matches("a") && noice.matches("[disabled]")){
  noice;
} else {
  noice;
}

if (noice.matches<HTMLAnchorElement>("a[disabled]")){
  noice;
} else {
  noice;
}
```

I did some testing to try and fix this scoping issue, and this seems to be working for all of the cases so far.

```ts
declare global {
  interface Element {
    matches<K extends keyof HTMLElementTagNameMap>(selectors: K): this is HTMLElementTagNameMap[K];
    matches<K extends keyof SVGElementTagNameMap>(selectors: K): this is SVGElementTagNameMap[K];
    matches(selectors: string): boolean; // Adding the original definition in this order here will prevent the final overload from being used where it shouldn't.
    matches<E extends Element = Element>(selectors: string): this is E;
  }
}

export {};
```

**Comment by BenjaminAster** [comment]
Should be fixed now, but again with `BetterTypeScript.GetElementTypeFromSelector<K>` instead of `{HTML/SVG/MathML}ElementTagNameMap[K]`, so that stuff like `.matches("a[disabled]")` still works and no splitting in `.matches("a")` and `.matches("[disabled]")` or type parameter (`.matches<HTMLAnchorElement>("a[disabled]")`) is required.
